sudo: required
services:
    - docker
    
before_install:
    - docker build -t vmehta229/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true vmehta229/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2.elasticbeanstalk.com"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-306476627547"
    bucket-path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"