sudo: required
services:
    - docker
    
before_install:
    - docker build -t vmehta229/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true vmehta229/docker-react npm run test